// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtqNe3dtvarC5pWaycU9muv7dSWinVC4',
    appId: '1:871609276040:web:7c7b9fa1baaab3caaa713d',
    messagingSenderId: '871609276040',
    projectId: 'babibeauty-app-f69d9',
    authDomain: 'babibeauty-app-f69d9.firebaseapp.com',
    storageBucket: 'babibeauty-app-f69d9.firebasestorage.app',
    measurementId: 'G-QV3XN01BYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCwX1VQc745Jp62ecZ3TNRdl6puW-6BdI',
    appId: '1:871609276040:android:1e2618fd97480a8baa713d',
    messagingSenderId: '871609276040',
    projectId: 'babibeauty-app-f69d9',
    storageBucket: 'babibeauty-app-f69d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6HythGcXj-VV2wcO3hPe48a5JsA_Y_EE',
    appId: '1:871609276040:ios:6db89ae1dbdc1252aa713d',
    messagingSenderId: '871609276040',
    projectId: 'babibeauty-app-f69d9',
    storageBucket: 'babibeauty-app-f69d9.firebasestorage.app',
    iosClientId: '871609276040-3afhfafgat7i83e7eulatqhj1nqbdp6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.babibeautyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6HythGcXj-VV2wcO3hPe48a5JsA_Y_EE',
    appId: '1:871609276040:ios:6db89ae1dbdc1252aa713d',
    messagingSenderId: '871609276040',
    projectId: 'babibeauty-app-f69d9',
    storageBucket: 'babibeauty-app-f69d9.firebasestorage.app',
    iosClientId: '871609276040-3afhfafgat7i83e7eulatqhj1nqbdp6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.babibeautyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtqNe3dtvarC5pWaycU9muv7dSWinVC4',
    appId: '1:871609276040:web:12b8750e58a52689aa713d',
    messagingSenderId: '871609276040',
    projectId: 'babibeauty-app-f69d9',
    authDomain: 'babibeauty-app-f69d9.firebaseapp.com',
    storageBucket: 'babibeauty-app-f69d9.firebasestorage.app',
    measurementId: 'G-XTXDP4FS55',
  );
}
